---
-   name: Check if Rancher HA container is running
    command: docker ps -a
    register: containers
-   debug: msg="{{ containers.stdout }}"
-   name: Start Rancher Server HA containers
    shell: "docker run --name=master -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 rancher/server --db-host {{ mysqldb }} --db-port 3306 --db-user {{ db_user }} --db-pass {{ db_pass }} --db-name {{ db_name }} --advertise-address {{ ansible_default_ipv4.address }}"
    when: not containers.stdout | search("rancher/server")

-   name: Wait for the Rancher servers to start
    action: command docker logs master
    register: rancher_logs
    until: rancher_logs.stdout.find("Listening on") != -1
    retries: 60
    delay: 10
    when: not containers.stdout | search("rancher/server")

-   debug: msg="You can connect to rancher server http://{{ ansible_default_ipv4.address }}:8080"
    when: not containers.stdout | search("rancher/server")

-   pause:
        seconds: 15
        prompt: "Waiting for Rancher to be fully up before continueing to build Kubernetes environment..."
    when: not containers.stdout | search("rancher/server")

-   name: Get Kubernetes Template ID
    action: uri
        method=GET
        url="http://{{ ansible_default_ipv4.address }}:8080/v2-beta/projectTemplates?name=kubernetes"
    register: kubernetes_template_id
    run_once: true
    delegate_to: "{{ master }}"

-   name: Store kubernetes_template_id
    local_action: shell echo {{ kubernetes_template_id.json.data[0].id }} > tmp/kubernetes_template_id.id
