---
-   name: Install python mysql bindings
    apt: name=python-mysqldb state=installed

-   name: Install mysql on DB node (root/password)
    raw: debconf-set-selections <<< 'mysql-server mysql-server/root_password password password' && debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password' && apt-get -y install mysql-server

-   name: Create db, user, and set up permission
    mysql_db:
        state: present
        name: "{{ db_name }}"
        login_password: password
-   mysql_user:
        name: "{{ db_user }}"
        host: localhost
        password: "{{ db_pass }}"
        priv: 'cattle.*:ALL,GRANT'
        state: present
        login_password: password
-   mysql_user:
        name: "{{ db_user }}"
        host: "%"
        password: "{{ db_pass }}"
        priv: 'cattle.*:ALL,GRANT'
        state: present
        login_password: password

-   name: Update mysql bind-address
    lineinfile:
        dest: /etc/mysql/my.cnf
        line: "[mysqld]\nbind-address            = 0.0.0.0"

-   name: Restart mysql Service
    service:
        name: mysql
        state: restarted
